name: to_ome_tiff
description: Convert any image format to ome.tiff
keywords:
  - microscopy
  - conversion
modules:
  - bioinfotongli/raw2ometiff
  - bioinfotongli/bioformats2raw
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'[file stem]' ]
  - reads:
      type: file
      description: |
        An image file to be converted.
      pattern: "*.png/tiff/tif/jpg/etc."
output:
  - ome_tif:
      type: file
      description: converted image file
      pattern: "*.ome_tif"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@bioinfotongli"
