---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "bioinfotongli_generatetiles"
description: a helper script to generate tiles from an 2D image file
keywords:
  - image
  - tiling
  - slicing
tools:
  - "bioinfotongli":
      description: ""
      homepage: ""
      documentation: ""
      tool_dev_url: ""
      doi: ""
      licence: 
      identifier: 

input:
  # Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', channels:[1,2] ]`

  - imgs:
      type: file
      description: raw images for segmentation
      pattern: "*.{tif,ome.tif,ome.tiff}"

output:
  #Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', channels:[0,1] ]`

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

  - segmentation:
      type: file
      description: a csv file contains the information of tiles
      pattern: "*.csv"

authors:
  - "@BioinfoTongLI"